/**
 *
 */
export enum DataType {
  behavior_animation_controller,
  behavior_animation,
  behavior_block,
  behavior_biome,
  behavior_dialogue,
  behavior_entity,
  behavior_feature_rule,
  behavior_function,
  behavior_feature,
  behavior_item,
  behavior_loot_table,
  behavior_manifest,
  behavior_recipe,
  behavior_script,
  behavior_spawn_rules,
  behavior_structure,
  behavior_trade,
  behavior_text,
  behavior_volume,

  resource_animation_controller,
  resource_animation,
  resource_attachable,
  resource_blocks,
  resource_biomes_client,
  resource_entity,
  resource_entity_model,
  resource_item,
  resource_manifest,
  resource_particle,
  resource_render_controller,
  resource_sounds,
  resource_sounds_definitions,
  resource_music_definitions,
  resource_texture_flipbook_atlas,
  resource_texture_item_atlas,
  resource_texture_terrain_atlas,
  resource_text,

  world_manifest,

  unknown,
}
