# This is a basic workflow to help you get started with Actions
name: Creating typescript includes

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - uses: DaanV2/Typescript-Action-Create-Includes@v1.2
        with: 
          folder: ${{github.workspace}}/server/src

      - uses: DaanV2/Typescript-Action-Create-Includes@v1.2
        with: 
          folder: ${{github.workspace}}/client/src

      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "Bot@Blockception.com"
          git config --global user.name "Blockception Bot"
          git add .
          git commit -m "auto: Generated typescript includes"
          git push
