name: Generate TS indexes

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate indexes 🖥️
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Client indexes
        uses: DaanV2/Typescript-Action-Create-Indexes@latest
        with:
          folder: ${{ github.workspace }}/client/src
          export_sub_index: false
          excludes: |
            *.test.ts
            index.ts

      - name: Server indexes
        uses: DaanV2/Typescript-Action-Create-Indexes@latest
        with:
          folder: ${{ github.workspace }}/server/src/Lib
          export_sub_index: false
          excludes: |
            *.test.ts
            index.ts

      - name: Server indexes
        uses: DaanV2/Typescript-Action-Create-Indexes@latest
        with:
          folder: ${{ github.workspace }}/server/src/Lib/Minecraft
          export_sub_index: true
          excludes: |
            *.test.ts
            index.ts

      - name: Shared indexes
        uses: DaanV2/Typescript-Action-Create-Indexes@latest
        with:
          folder: ${{ github.workspace }}/shared
          export_sub_index: false
          excludes: |
            *.test.ts
            index.ts

      - name: ✏️ Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "orbi@blockception.com"
          git config --global user.name "Orbi-bot"
          git add .
          git commit -m "auto: generated typescript includes"
          git push
