# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Unit Test Client

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:      
  test:
    name: Test and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd ${{ github.workspace }}/server
      - name: Build
        run: npm ci
      - name: Test
        run: npm test
