# This is a basic workflow to help you get started with Actions
name: publish-universal-to-vscode

# Controls when the workflow will run
on:   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: ["increase version"]
    branches: [main]
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  universal:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: npm run test
      - name: Build 
        run: npx vsce package
        env:
          VSCE_PAT: ${{ secrets.vsce }}

      - uses: actions/upload-artifact@v2
        with:
          name: universal
          path: "*.vsix"
          
  publish:  
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [universal]
    steps:
      - uses: actions/download-artifact@v2
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.vsce }}
