# This is a basic workflow to help you get started with Actions
name: publish-universal-to-vscode

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Build
        run: npm ci

      - name: Test
        run: npm test

  universal:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Setup Node Project
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npx vsce package
        env:
          VSCE_PAT: ${{ secrets.vsce }}

      ## Check if the webpacked version is still good
      - name: Test
        run: npm test

      - uses: actions/upload-artifact@v3
        with:
          name: universal
          path: "*.vsix"

  publish:
    if: ${{ needs.test.result == 'success' && needs.universal.result == 'success' }}
    runs-on: ubuntu-latest
    needs: [universal, test]
    steps:
      - uses: actions/download-artifact@v2
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.vsce }}
